<?php

namespace AppBundle\Repository;

/**
 * PersonaContactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaContactoRepository extends \Doctrine\ORM\EntityRepository
{
}
