<?php

namespace AppBundle\Repository;

/**
 * PersonaDireccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaDireccionRepository extends \Doctrine\ORM\EntityRepository
{
}
