<?php

namespace AppBundle\Repository;

/**
 * ProductoCategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoCategoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
