<?php

namespace AppBundle\Repository;

/**
 * ProductoStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoStockRepository extends \Doctrine\ORM\EntityRepository
{
}
