<?php

namespace AppBundle\Repository;

/**
 * ProductoPrecioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoPrecioRepository extends \Doctrine\ORM\EntityRepository
{
}
