easy_admin:
    entities:
        ProductoCategoria:
            class: AppBundle\Entity\ProductoCategoria
            label: 'Categoria de producto'
            list:
                title: 'Listado de %%entity_label%%s'
                actions:
                    - { name: 'new', label: 'Nuevo %%entity_label%%' }
                fields:
                    - { property: 'nombre' }
                    - { property: 'descripcion' }
                    - { property: 'activo' }
            show:
                title: '%%entity_label%% (#%%entity_id%%)'
            form:
                title:  'Nueva %%entity_label%%'
                fields:
                    - nombre
                    - descripcion
                    - activo
#
            edit:
                title:  'Editar %%entity_label%%'
            edit:
                title:  'Editar %%entity_label%%'